### ISSUE TITLE
Installation attempt

### ISSUE THREAD

**Issue by Sbatushe** [jbuchermn/newm#2]
I tried to install this compositor on void linux with theese commands:
```
sudo xbps-install python3-psutil-5.8.0_1
git clone https://github.com/jbuchermn/newm
cd newm
python3 setup.py build
python3 setup.py install
./scripts-3.9/start-newm
```
but the compositor doesn't start. I tried to start it manually from a python3 console using `from newm import run` but seems like pywm is missing:

```
>>> from newm import run
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/newm-0.0.9-py3.9.egg/newm/__init__.py", line 9, in <module>
    from .run import run
  File "/usr/lib/python3.9/site-packages/newm-0.0.9-py3.9.egg/newm/run.py", line 5, in <module>
    from .layout import Layout
  File "/usr/lib/python3.9/site-packages/newm-0.0.9-py3.9.egg/newm/layout.py", line 12, in <module>
    from pywm import (
ModuleNotFoundError: No module named 'pywm'

```
I'm wondering if [this](http://pywm.sourceforge.net/) is pywm, but i'm unsure, since it's a Xorg wm. If this is the case I don't know how to install it because it's not installable via pip3.

**Comment by jbuchermn** [comment]
Please check out branch v0.1 - this contains a more detailed documentation for installation. However it is still a work in progress, therefore not merged into master.

Upshot is, you should be able to install it via pip3 by giving the github path. It does depend on pywm, but indeed that's another package (by me), which should be installable via pip3 as well. Doing so (`pip3 install git+https://github.com/jbuchermn/pywm@v0.1`) compiles the compositor, which can fail if there are dependencies missing - just copy the error message here in that case.

**Comment by Sbatushe** [comment]
Seems like an error occurred while installing pywm, during the meson build, where i can find the logs?
```
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/jbuchermn/pywm@v0.1
  Cloning https://github.com/jbuchermn/pywm (to revision v0.1) to /tmp/pip-req-build-19d03cxn
  Running command git clone -q https://github.com/jbuchermn/pywm /tmp/pip-req-build-19d03cxn
  Running command git checkout -b v0.1 --track origin/v0.1
  Si è passati a un nuovo branch 'v0.1'
  Branch 'v0.1' impostato per tracciare il branch remoto 'v0.1' da 'origin'.
  Resolved https://github.com/jbuchermn/pywm to commit b3f8a0df7955df52dd07a2504a32b018ac110dc8
  Running command git submodule update --init --recursive -q
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-19d03cxn/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-19d03cxn/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-u88unni7
         cwd: /tmp/pip-req-build-19d03cxn/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-19d03cxn/setup.py", line 9, in <module>
        raise Exception("Fatal: Error executing 'meson build': \n%r" % stderr)
    Exception: Fatal: Error executing 'meson build':
    b''
    ----------------------------------------
WARNING: Discarding git+https://github.com/jbuchermn/pywm@v0.1. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by jbuchermn** [comment]
Unfortunately there is no error log - I don't know why this happens. To get more detailed info, can you try without pip?
`git clone https://github.com/jbuchermn/pywm
cd pywm
git checkout v0.1
meson build
ninja -C build install`

**Comment by Sbatushe** [comment]
It works, i solved a bit of wlroots dependencies, pywm dependencies (just python3-devel) and used start-newm from a tty, thanks for the help! I'll play around with this compositor :)
