### ISSUE TITLE
Command errored out with exit status 1

### ISSUE THREAD

**Issue by rosharp** [jbuchermn/newm#54]
After running:
`pip3 install --user git+https://github.com/jbuchermn/pywm`
I ended up with an error below:
```
Collecting git+https://github.com/jbuchermn/pywm
  Cloning https://github.com/jbuchermn/pywm to /private/var/folders/7h/bmp0qh9d4jld9yvl5j5f9ryr0000gn/T/pip-req-build-0d_s0os2
  Running command git clone --filter=blob:none -q https://github.com/jbuchermn/pywm /private/var/folders/7h/bmp0qh9d4jld9yvl5j5f9ryr0000gn/T/pip-req-build-0d_s0os2
  Resolved https://github.com/jbuchermn/pywm to commit 63f32828a1ac0d7e961727ceb84e68d6ff642d4a
  Running command git submodule update --init --recursive -q

Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7h/bmp0qh9d4jld9yvl5j5f9ryr0000gn/T/pip-req-build-0d_s0os2/setup.py'"'"'; __file__='"'"'/private/var/folders/7h/bmp0qh9d4jld9yvl5j5f9ryr0000gn/T/pip-req-build-0d_s0os2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/7h/bmp0qh9d4jld9yvl5j5f9ryr0000gn/T/pip-pip-egg-info-nslcgr2o
       cwd: /private/var/folders/7h/bmp0qh9d4jld9yvl5j5f9ryr0000gn/T/pip-req-build-0d_s0os2/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/7h/bmp0qh9d4jld9yvl5j5f9ryr0000gn/T/pip-req-build-0d_s0os2/setup.py", line 9, in <module>
      raise Exception("Fatal: Error executing 'meson build': \n%r\n%r" % (stdout, stderr))
  Exception: Fatal: Error executing 'meson build':
  b'The Meson build system\nVersion: 0.61.1\nSource dir: /private/var/folders/7h/bmp0qh9d4jld9yvl5j5f9ryr0000gn/T/pip-req-build-0d_s0os2\nBuild dir: /private/var/folders/7h/bmp0qh9d4jld9yvl5j5f9ryr0000gn/T/pip-req-build-0d_s0os2/build\nBuild type: native build\nProject name: pywm\nProject version: 0.1.0\nC compiler for the host machine: cc (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")\nC linker for the host machine: cc ld64 711\nHost machine cpu family: x86_64\nHost machine cpu: x86_64\n\nExecuting subproject wlroots \n\nwlroots| Project name: wlroots\nwlroots| Project version: 0.15.0\nwlroots| C compiler for the host machine: cc (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")\nwlroots| C linker for the host machine: cc ld64 711\nwlroots| Compiler for C supports arguments -Wundef: YES\nwlroots| Compiler for C supports arguments -Wlogical-op: NO\nwlroots| Compiler for C supports arguments -Wmissing-include-dirs: YES\nwlroots| Compiler for C supports arguments -Wold-style-definition: YES\nwlroots| Compiler for C supports arguments -Wpointer-arith: YES\nwlroots| Compiler for C supports arguments -Winit-self: YES\nwlroots| Compiler for C supports arguments -Wstrict-prototypes: YES\nwlroots| Compiler for C supports arguments -Wimplicit-fallthrough=2: NO\nwlroots| Compiler for C supports arguments -Wendif-labels: YES\nwlroots| Compiler for C supports arguments -Wstrict-aliasing=2: YES\nwlroots| Compiler for C supports arguments -Woverflow: YES\nwlroots| Compiler for C supports arguments -Wmissing-prototypes: YES\nwlroots| Compiler for C supports arguments -Walloca: YES\nwlroots| Compiler for C supports arguments -Wno-missing-braces: YES\nwlroots| Compiler for C supports arguments -Wno-missing-field-initializers: YES\nwlroots| Compiler for C supports arguments -Wno-unused-parameter: YES\nwlroots| Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES\nwlroots| Found pkg-config: /usr/local/bin/pkg-config (0.29.2)\nwlroots| Found CMake: /usr/local/bin/cmake (3.22.1)\nwlroots| Run-time dependency wayland-server found: NO (tried pkgconfig, framework and cmake)\nwlroots| Looking for a fallback subproject for the dependency wayland-server\n\nsubprojects/wlroots/meson.build:101:0: ERROR: Neither a subproject directory nor a wayland.wrap file was found.\n\nA full log can be found at /private/var/folders/7h/bmp0qh9d4jld9yvl5j5f9ryr0000gn/T/pip-req-build-0d_s0os2/build/meson-logs/meson-log.txt\n'
  b''
  ----------------------------------------
WARNING: Discarding git+https://github.com/jbuchermn/pywm. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I am currently running macOS Monterey 12.1

**Comment by rosharp** [comment]
I'm sorry, I didn't noticed that in the video I saw you were running Arch on a Mac. Thank you for an advice, though! I'll definitely try it out.

**Comment by jbuchermn** [comment]
Ah okay I see. Yeah it's a MacBook, but it's running Linux :)
